# Generated by Django 2.2.6 on 2019-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='e_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='n_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.AddField(
            model_name='room',
            name='grid',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='homex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='homey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
