# Generated by Django 2.2.6 on 2019-10-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20191024_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='grid',
            field=models.TextField(default=''),
        ),
    ]
