# Generated by Django 2.2.6 on 2019-10-25 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20191024_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
