# Generated by Django 2.2.6 on 2019-10-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20191025_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
